name: Build and deploy Python app to Azure Web App - flask-test-app77

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Add these permissions at the top level
permissions:
  contents: read
  id-token: write  # This is crucial for OIDC authentication

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Repeat permissions for the job

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install gunicorn

      - name: List files for debugging
        run: |
          pwd
          ls -la

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x 'venv/*'

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read
      id-token: write  # Ensure write permissions for id-token

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: List files after unzip
        run: ls -la

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B01675113CD348C7984F21EA9A696E41 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_109D8B86D5FE442BB92A10C884A8EF00 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1E41304C04F74404818E1C6D992A0051 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'flask-test-app77'
          slot-name: 'Production'
          startup-command: 'gunicorn --bind 0.0.0.0:8000 wsgi:application'
